import React from 'react';

export interface Post {
  slug: string;
  title: string;
  date: string;
  component: React.LazyExoticComponent<React.FC<{}>>;
}

export const ALL_POSTS: Omit<Post, 'component'>[] = [
    { slug: 'will-gold-hit-5000-an-ounce', title: 'Will gold hit $5000 an ounce?', date: '2024-08-01' },
    { slug: 'how-much-is-a-22-carat-gold', title: 'How much is a 22 carat gold?', date: '2024-08-01' },
    { slug: 'is-gold-22k-or-24k', title: 'Is gold 22k or 24k?', date: '2024-08-01' },
    { slug: 'what-is-the-price-of-gold-in-dollars-today', title: 'What is the price of gold in dollars today?', date: '2024-08-01' },
    { slug: 'gold-price', title: 'Gold price', date: '2024-07-31' },
    { slug: 'gold-price-chart', title: 'Gold price chart', date: '2024-07-30' },
    { slug: 'gold-price-live', title: 'Gold price live', date: '2024-07-29' },
    { slug: 'gold-price-22k', title: 'Gold price 22K', date: '2024-07-28' },
    { slug: 'silver-price-today', title: 'Silver price today', date: '2024-07-27' },
    { slug: 'gold-stock', title: 'Gold stock', date: '2024-07-26' },
    { slug: 'gold-price-prediction', title: 'Gold price prediction', date: '2024-07-25' },
    { slug: 'gold-price-per-gram', title: 'Gold price per gram', date: '2024-07-24' },
    { slug: 'how-much-is-silver-worth-today', title: 'How much is silver worth today?', date: '2024-07-23' },
    { slug: 'what-is-silver-made-of', title: 'What is silver made of?', date: '2024-07-22' },
    { slug: 'what-is-the-price-of-silver-1-kg', title: 'What is the price of silver 1 kg?', date: '2024-07-21' },
    { slug: 'is-silver-stronger-than-gold', title: 'Is silver stronger than gold?', date: '2024-07-20' },
    { slug: 'silver-price-chart', title: 'Silver price chart', date: '2024-07-19' },
    { slug: 'silver-color', title: 'Silver color', date: '2024-07-18' },
    { slug: 'silver-stock', title: 'Silver stock', date: '2024-07-17' },
    { slug: 'buy-silver', title: 'Buy silver', date: '2024-07-16' },
    { slug: 'silver-element', title: 'Silver element', date: '2024-07-15' },
    { slug: 'silver-price-history', title: 'Silver price History', date: '2024-07-14' },
    { slug: 'silver-metal', title: 'Silver metal', date: '2024-07-13' },
    { slug: 'silver-atom', title: 'Silver atom', date: '2024-07-12' },
    { slug: 'is-platinum-worth-more-than-gold', title: 'Is platinum worth more than gold?', date: '2024-07-11' },
    { slug: 'what-is-the-price-of-1-gram-of-platinum', title: 'What is the price of 1 gram of platinum?', date: '2024-07-10' },
    { slug: 'how-much-is-platinum', title: 'How much is platinum?', date: '2024-07-09' },
    { slug: 'is-platinum-rare', title: 'Is platinum rare?', date: '2024-07-08' },
    { slug: 'platinum-price', title: 'Platinum price', date: '2024-07-07' },
    { slug: 'platinum-jewellery', title: 'Platinum jewellery', date: '2024-07-06' },
    { slug: 'platinum-metal', title: 'Platinum metal', date: '2024-07-05' },
    { slug: 'platinum-color', title: 'Platinum color', date: '2024-07-04' },
    { slug: 'platinum-element', title: 'Platinum element', date: '2024-07-03' },
    { slug: 'platinum-use', title: 'Platinum use', date: '2024-07-02' },
    { slug: 'platinum-vs-gold', title: 'Platinum vs gold', date: '2024-07-01' },
    { slug: 'platinum-chemical-formula', title: 'Platinum chemical formula', date: '2024-06-30' },
    // New Diamond Posts
    { slug: 'what-are-the-4cs-of-diamonds', title: 'What Are The 4Cs of Diamonds? Cut, Color, Clarity, and Carat', date: '2024-08-02' },
    { slug: 'how-are-diamonds-formed', title: 'How Are Diamonds Formed Naturally?', date: '2024-08-02' },
    { slug: 'lab-grown-vs-natural-diamonds', title: 'Lab-Grown vs. Natural Diamonds: What\'s the Difference?', date: '2024-08-02' },
    { slug: 'how-to-tell-if-a-diamond-is-real', title: 'How to Tell if a Diamond is Real: 5 Easy Tests', date: '2024-08-02' },
    { slug: 'diamond-price-per-carat-guide', title: 'Diamond Price Per Carat: A Complete Guide', date: '2024-08-02' },
    { slug: 'investing-in-diamonds-pros-and-cons', title: 'Investing in Diamonds: Pros and Cons', date: '2024-08-02' },
    { slug: 'most-famous-diamonds-in-the-world', title: 'The Most Famous Diamonds in the World', date: '2024-08-02' },
    { slug: 'what-is-a-blood-diamond', title: 'What is a Blood Diamond? Understanding Conflict Diamonds', date: '2024-08-02' },
    { slug: 'different-diamond-shapes-explained', title: 'Different Diamond Shapes Explained: From Round to Princess', date: '2024-08-02' },
    { slug: 'how-to-clean-diamond-jewelry', title: 'How to Clean Diamond Jewelry at Home', date: '2024-08-02' },
];

export const POSTS_MAP = {
    'will-gold-hit-5000-an-ounce': React.lazy(() => import('../pages/blog/WillGoldHit5000AnOunce')),
    'how-much-is-a-22-carat-gold': React.lazy(() => import('../pages/blog/HowMuchIsA22CaratGold')),
    'is-gold-22k-or-24k': React.lazy(() => import('../pages/blog/IsGold22kOr24k')),
    'what-is-the-price-of-gold-in-dollars-today': React.lazy(() => import('../pages/blog/WhatIsThePriceOfGoldInDollarsToday')),
    'gold-price': React.lazy(() => import('../pages/blog/GoldPrice')),
    'gold-price-chart': React.lazy(() => import('../pages/blog/GoldPriceChart')),
    'gold-price-live': React.lazy(() => import('../pages/blog/GoldPriceLive')),
    'gold-price-22k': React.lazy(() => import('../pages/blog/GoldPrice22K')),
    'silver-price-today': React.lazy(() => import('../pages/blog/SilverPriceToday')),
    'gold-stock': React.lazy(() => import('../pages/blog/GoldStock')),
    'gold-price-prediction': React.lazy(() => import('../pages/blog/GoldPricePrediction')),
    'gold-price-per-gram': React.lazy(() => import('../pages/blog/GoldPricePerGram')),
    'how-much-is-silver-worth-today': React.lazy(() => import('../pages/blog/HowMuchIsSilverWorthToday')),
    'what-is-silver-made-of': React.lazy(() => import('../pages/blog/WhatIsSilverMadeOf')),
    'what-is-the-price-of-silver-1-kg': React.lazy(() => import('../pages/blog/WhatIsThePriceOfSilver1Kg')),
    'is-silver-stronger-than-gold': React.lazy(() => import('../pages/blog/IsSilverStrongerThanGold')),
    'silver-price-chart': React.lazy(() => import('../pages/blog/SilverPriceChart')),
    'silver-color': React.lazy(() => import('../pages/blog/SilverColor')),
    'silver-stock': React.lazy(() => import('../pages/blog/SilverStock')),
    'buy-silver': React.lazy(() => import('../pages/blog/BuySilver')),
    'silver-element': React.lazy(() => import('../pages/blog/SilverElement')),
    'silver-price-history': React.lazy(() => import('../pages/blog/SilverPriceHistory')),
    'silver-metal': React.lazy(() => import('../pages/blog/SilverMetal')),
    'silver-atom': React.lazy(() => import('../pages/blog/SilverAtom')),
    'is-platinum-worth-more-than-gold': React.lazy(() => import('../pages/blog/IsPlatinumWorthMoreThanGold')),
    'what-is-the-price-of-1-gram-of-platinum': React.lazy(() => import('../pages/blog/WhatIsThePriceOf1GramOfPlatinum')),
    'how-much-is-platinum': React.lazy(() => import('../pages/blog/HowMuchIsPlatinum')),
    'is-platinum-rare': React.lazy(() => import('../pages/blog/IsPlatinumRare')),
    'platinum-price': React.lazy(() => import('../pages/blog/PlatinumPrice')),
    'platinum-jewellery': React.lazy(() => import('../pages/blog/PlatinumJewellery')),
    'platinum-metal': React.lazy(() => import('../pages/blog/PlatinumMetal')),
    'platinum-color': React.lazy(() => import('../pages/blog/PlatinumColor')),
    'platinum-element': React.lazy(() => import('../pages/blog/PlatinumElement')),
    'platinum-use': React.lazy(() => import('../pages/blog/PlatinumUse')),
    'platinum-vs-gold': React.lazy(() => import('../pages/blog/PlatinumVsGold')),
    'platinum-chemical-formula': React.lazy(() => import('../pages/blog/PlatinumChemicalFormula')),
    // New Diamond Posts
    'what-are-the-4cs-of-diamonds': React.lazy(() => import('../pages/blog/WhatAreThe4csOfDiamonds')),
    'how-are-diamonds-formed': React.lazy(() => import('../pages/blog/HowAreDiamondsFormed')),
    'lab-grown-vs-natural-diamonds': React.lazy(() => import('../pages/blog/LabGrownVsNaturalDiamonds')),
    'how-to-tell-if-a-diamond-is-real': React.lazy(() => import('../pages/blog/HowToTellIfADiamondIsReal')),
    'diamond-price-per-carat-guide': React.lazy(() => import('../pages/blog/DiamondPricePerCaratGuide')),
    'investing-in-diamonds-pros-and-cons': React.lazy(() => import('../pages/blog/InvestingInDiamondsProsAndCons')),
    'most-famous-diamonds-in-the-world': React.lazy(() => import('../pages/blog/MostFamousDiamondsInTheWorld')),
    'what-is-a-blood-diamond': React.lazy(() => import('../pages/blog/WhatIsABloodDiamond')),
    'different-diamond-shapes-explained': React.lazy(() => import('../pages/blog/DifferentDiamondShapesExplained')),
    'how-to-clean-diamond-jewelry': React.lazy(() => import('../pages/blog/HowToCleanDiamondJewelry')),
};
